name: Test Login using NUnit and CI (with GitHub Actions) | © 2023 KhangPhamBM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Distribute jar-war file
        run: |
          mkdir staging
          cp target/*.jar staging

      - name: Make hyperlink to jar-war file
        uses: actions/upload-artifact@v1
        with:
          name: nha-tuyen-dung-download-jar.zip
          path: staging
